export const authConstants = {

    REPLENISH_REQUEST: 'PARTNER_REPLENISH_REQUEST',
    REPLENISH_SUCCESS: 'PARTNER_REPLENISH_SUCCESS',
    REPLENISH_FAILURE: 'PARTNER_REPLENISH_FAILURE',

    REGISTER_REQUEST: 'PARTNER_REGISTER_REQUEST',
    REGISTER_PROCESSED: 'USER_REGISTER_PROCESSED',
    REGISTER_SUCCESS: 'PARTNER_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'PARTNER_REGISTER_FAILURE',

    LOGIN_REQUEST: 'PARTNER_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'PARTNER_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'PARTNER_LOGIN_FAILURE',

    LOGOUT: 'PARTNER_LOGOUT',
};