export const deliveryConstants = {

   GET_DELIVERY_REQUEST: 'PARTNER_GET_DELIVERY_REQUEST',
   GET_DELIVERY_SUCCESS: 'PARTNER_GET_DELIVERY_SUCCESS',
   GET_DELIVERY_FAILURE: 'PARTNER_GET_DELIVERY_FAILURE',

};