export const locationConstants = {

    LOCATION_REQUEST: 'USER_LOCATION_REQUEST',
    LOCATION_SUCCESS: 'USER_LOCATION_SUCCESS',
    LOCATION_FAILURE: 'USER_LOCATION_FAILURE',

    WATCH_LOCATION_REQUEST: 'USER_WATCH_LOCATION_REQUEST',
    WATCH_LOCATION_SUCCESS: 'USER_WATCH_LOCATION_SUCCESS',
    WATCH_LOCATION_FAILURE: 'USER_WATCH_LOCATION_FAILURE',

    GET_ADDRESS_REQUEST: 'GET_USER_ADDRESS_REQUEST',
    GET_ADDRESS_SUCCESS: 'GET_USER_ADDRESS_SUCCESS',
    GET_ADDRESS_FAILURE: 'GET_USER_ADDRESS_FAILURE'
};