export const authConstants = {

    REPLENISH_REQUEST: 'USER_REPLENISH_REQUEST',
    REPLENISH_SUCCESS: 'USER_REPLENISH_SUCCESS',
    REPLENISH_FAILURE: 'USER_REPLENISH_FAILURE',

    REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
    REGISTER_PROCESSED: 'USER_REGISTER_PROCESSED',
    REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USER_REGISTER_FAILURE',

    LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USER_LOGIN_FAILURE',

    LOGOUT: 'USER_LOGOUT',
};