export const orderConstants = {

    GET_ONGOING_ORDER_REQUEST: 'GET_SELLER_ONGOING_PRODUCT_REQUEST',
    GET_ONGOING_ORDER_SUCCESS: 'GET_SELLER_ONGOING_PRODUCT_SUCCESS',
    GET_ONGOING_ORDER_FAILURE: 'GET_SELLER_ONGOING_PRODUCT_FAILURE',
    
    GET_COMPLETED_ORDER_REQUEST: 'GET_SELLER_COMPLETED_PRODUCT_REQUEST',
    GET_COMPLETED_ORDER_SUCCESS: 'GET_SELLER_COMPLETED_PRODUCT_SUCCESS',
    GET_COMPLETED_ORDER_FAILURE: 'GET_SELLER_COMPLETED_PRODUCT_FAILURE'
};