export const productConstants = {

    GET_PRODUCT_REQUEST: 'GET_SELLER_PRODUCT_REQUEST',
    GET_PRODUCT_SUCCESS: 'GET_SELLER_PRODUCT_SUCCESS',
    GET_PRODUCT_FAILURE: 'GET_SELLER_PRODUCT_FAILURE'
};