export const cartConstants = {

    ADD_REQUEST: 'CART_ADD_REQUEST',
    ADD_SUCCESS: 'CART_ADD_SUCCESS',
    ADD_FAILURE: 'CART_ADD_FAILURE',

    REMOVE_REQUEST: 'CART_REMOVE_REQUEST',
    REMOVE_SUCCESS: 'CART_REMOVE_SUCCESS',
    REMOVE_FAILURE: 'CART_REMOVE_FAILURE',

    GET_REQUEST: 'CART_GET_REQUEST',
    GET_SUCCESS: 'CART_GET_SUCCESS',
    GET_FAILURE: 'CART_GET_FAILURE',

    CLEAR_REQUEST: 'CART_CLEAR_REQUEST',
    CLEAR_SUCCESS: 'CART_CLEAR_SUCCESS',
    CLEAR_FAILURE: 'CART_CLEAR_FAILURE',

};