export const wishlistConstants = {

    ADD_REQUEST: 'WISHLIST_ADD_REQUEST',
    ADD_SUCCESS: 'WISHLIST_ADD_SUCCESS',
    ADD_FAILURE: 'WISHLIST_ADD_FAILURE',

    REMOVE_REQUEST: 'WISHLIST_REMOVE_REQUEST',
    REMOVE_SUCCESS: 'WISHLIST_REMOVE_SUCCESS',
    REMOVE_FAILURE: 'WISHLIST_REMOVE_FAILURE',

    GET_REQUEST: 'WISHLIST_GET_REQUEST',
    GET_SUCCESS: 'WISHLIST_GET_SUCCESS',
    GET_FAILURE: 'WISHLIST_GET_FAILURE',

};