
export const deliveriesData = [
    {
        "id": 1,
        "customerName": "Joe",
        "time": "1 min",
        "earning": "23",
        "shopName": "Seven 7",
        "closingTime": "230 ms away",
        "customerImage": require('../../../assets/images/temp/profile1.png'),
        "shopImage": require('../../../assets/images/temp/shop.png'),
        "customerCoordinate": { latitude: 12.919840, longitude: 80.159404 },
        "shopCoordinate": { latitude: 12.918200, longitude: 80.159532 },
    }, {
        "id": 2,
        "customerName": "lucy",
        "time": "2 min",
        "earning": "20",
        "shopName": "Seven 7",
        "closingTime": "230 ms away",
        "customerImage": require('../../../assets/images/temp/profile1.png'),
        "shopImage": require('../../../assets/images/temp/shop.png'),
        "customerCoordinate": { latitude: 12.915840, longitude: 80.158404 },
        "shopCoordinate": { latitude: 12.912200, longitude: 80.157532 },
    }, {
        "id": 3,
        "customerName": "J vijay",
        "time": "4 min",
        "earning": "15",
        "shopName": "Seven 7",
        "closingTime": "230 ms away",
        "customerImage": require('../../../assets/images/temp/profile1.png'),
        "shopImage": require('../../../assets/images/temp/shop.png'),
        "customerCoordinate": { latitude: 12.916840, longitude: 80.156404 },
        "shopCoordinate": { latitude: 12.918200, longitude: 80.159532 },
    }, {
        "id": 4,
        "customerName": "mary",
        "time": "5 min",
        "earning": "32",
        "shopName": "Seven 7",
        "closingTime": "230 ms away",
        "customerImage": require('../../../assets/images/temp/profile1.png'),
        "shopImage": require('../../../assets/images/temp/shop.png'),
        "customerCoordinate": { latitude: 12.916840, longitude: 80.155404 },
        "shopCoordinate": { latitude: 12.915200, longitude: 80.156532 },
    }, {
        "id": 5,
        "customerName": "alice",
        "time": "5 min",
        "earning": "17",
        "shopName": "Seven 7",
        "closingTime": "230 ms away",
        "customerImage": require('../../../assets/images/temp/profile1.png'),
        "shopImage": require('../../../assets/images/temp/shop.png'),
        "customerCoordinate": { latitude: 12.919840, longitude: 80.159404 },
        "shopCoordinate": { latitude: 12.918200, longitude: 80.159532 },
    }
]

